### ISSUE TITLE
自动下载chrome时SSL报错

### ISSUE THREAD

**Issue by Elmeir** [felinae98/nonebot-hk-reporter#11]
通过nonebot安装的插件
已设置变量HK_REPORTER_USE_LOCAL为true解决

以下是日志

06-18 12:19:52 [INFO] nonebot | Running NoneBot...
06-18 12:19:52 [DEBUG] nonebot | Loaded adapters: cqhttp
06-18 12:19:52 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
06-18 12:19:52 [INFO] uvicorn | Started reloader process [4180] using watchgod
06-18 12:19:53 [INFO] nonebot | NoneBot is initializing...
06-18 12:19:53 [INFO] nonebot | Current Env: dev
06-18 12:19:53 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev'}
06-18 12:19:53 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
06-18 12:19:53 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
06-18 12:19:54 [ERROR] nonebot | Failed to import "nonebot_hk_reporter"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

**Comment by felinae98** [comment]
报的错是握手时SSL证书不正确，可能和你的网络环境有关

**Comment by felinae98** [comment]
如果没有别的问题就关闭了
