### ISSUE TITLE
在Nonebot插件广场无法安装，直接克隆运行不正常

### ISSUE THREAD

**Issue by Soarniner** [felinae98/nonebot-hk-reporter#2]
Nonebot插件广场安装显示
PS C:\Users\Administrator\PRTS> nb plugin install nonebot_hk_reporter
ERROR: Could not find a version that satisfies the requirement nonebot-hk-reporter
ERROR: No matching distribution found for nonebot-hk-reporter
python已为最新版，pip已为最新版

直接克隆下来运行显示
02-26 16:35:27 [INFO] uvicorn | ('127.0.0.1', 60395) - "WebSocket /cqhttp/ws" [accepted]
02-26 16:35:27 [INFO] nonebot | WebSocket Connection from CQHTTP Bot 340******67 Accepted!
02-26 16:36:16 [INFO] nonebot | CQHTTP 3403117467 | [message.group.normal]: Message 682*****46 from 284*****647@[群:1045****72] "添加订阅"
02-26 16:36:16 [DEBUG] nonebot | Checking for matchers in priority 1...
02-26 16:36:16 [DEBUG] nonebot | Checking for matchers in priority 5...

群里@bot无响应

完整情况
PS C:\Users\Administrator\PRTS> nb run
02-26 16:34:50 [INFO] nonebot | NoneBot is initializing...
02-26 16:34:50 [INFO] nonebot | Current Env: dev
02-26 16:34:50 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'),
'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': se
t(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(second
s=120), 'environment': 'dev'}
02-26 16:34:50 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
02-26 16:34:50 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
02-26 16:34:50 [INFO] nonebot | Succeeded to import "auto_agree"
02-26 16:34:50 [ERROR] nonebot | Failed to import "hk_reporter"
Traceback (most recent call last):
  File "c:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\python\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\program files\python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "c:\program files\python\lib\site-packages\nb_cli\handlers.py", line 44, in run_bot
    module = importlib.import_module(module_name)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 11, in <module>
    nonebot.load_plugins('src/plugins')
  File "c:\program files\python\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "c:\program files\python\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\hk_reporter\__init__.py", line 3, in <module>
    from . import config_manager
  File "src/plugins\hk_reporter\config_manager.py", line 10, in <module>
    from .platform import platform_manager
  File "src/plugins\hk_reporter\platform\__init__.py", line 1, in <module>
    from .bilibili import Bilibili
  File "src/plugins\hk_reporter\platform\bilibili.py", line 7, in <module>
    from ..post import Post
  File "src/plugins\hk_reporter\post.py", line 12, in <module>
    class Post:
  File "src/plugins\hk_reporter\post.py", line 21, in Post
    pics: list[str] = field(default_factory=list)
TypeError: 'type' object is not subscriptable
02-26 16:34:50 [INFO] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
02-26 16:34:50 [INFO] nonebot | Running NoneBot...
02-26 16:34:50 [DEBUG] nonebot | Loaded adapters: cqhttp
02-26 16:34:50 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
02-26 16:34:50 [INFO] uvicorn | Started reloader process [1224] using statreload
02-26 16:34:51 [INFO] nonebot | NoneBot is initializing...
02-26 16:34:51 [INFO] nonebot | Current Env: dev
02-26 16:34:51 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'),
'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': se
t(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(second
s=120), 'environment': 'dev'}
02-26 16:34:51 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
02-26 16:34:51 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
02-26 16:34:51 [INFO] nonebot | Succeeded to import "auto_agree"
02-26 16:34:51 [ERROR] nonebot | Failed to import "hk_reporter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "c:\program files\python\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\program files\python\lib\site-packages\uvicorn\main.py", line 397, in serve
    config.load()
  File "c:\program files\python\lib\site-packages\uvicorn\config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\program files\python\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 11, in <module>
    nonebot.load_plugins('src/plugins')
  File "c:\program files\python\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "c:\program files\python\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\hk_reporter\__init__.py", line 3, in <module>
    from . import config_manager
  File "src/plugins\hk_reporter\config_manager.py", line 10, in <module>
    from .platform import platform_manager
  File "src/plugins\hk_reporter\platform\__init__.py", line 1, in <module>
    from .bilibili import Bilibili
  File "src/plugins\hk_reporter\platform\bilibili.py", line 7, in <module>
    from ..post import Post
  File "src/plugins\hk_reporter\post.py", line 12, in <module>
    class Post:
  File "src/plugins\hk_reporter\post.py", line 21, in Post
    pics: list[str] = field(default_factory=list)
TypeError: 'type' object is not subscriptable

**Comment by felinae98** [comment]
将python版本升级到3.9及以上

**Comment by Soarniner** [comment]
装了3.9才试的
试了prts-forward-bot那个也是一模一样的情况

**Comment by Soarniner** [comment]
好吧我的锅，我去看了一下Python版本是3.8.6，但是我装了3.9.2的包的，我再试一下

**Comment by felinae98** [comment]
0.2.4修复了nb-cli安装本插件的问题（但是需要python3.9）

**Comment by Soarniner** [comment]
换了Python 3.9后正常安装了，但是群里@机器人仍然无响应

02-26 20:14:24 [INFO] uvicorn | ('127.0.0.1', 49693) - "WebSocket /cqhttp/ws" [accepted]
02-26 20:14:24 [INFO] nonebot | WebSocket Connection from CQHTTP Bot 34******467 Accepted!
02-26 20:14:58 [INFO] nonebot | CQHTTP 34********467 | [message.group.normal]: Message -1465708659 from 28*****647@[群:104*******72] "添加订阅"
02-26 20:14:58 [DEBUG] nonebot | Checking for matchers in priority 1...
02-26 20:14:58 [DEBUG] nonebot | Checking for matchers in priority 5...
02-26 20:16:59 [INFO] nonebot | CQHTTP 34********67 | [message.group.normal]: Message 833248823 from 284******47@[群:1045*******72] "查询订阅"
02-26 20:16:59 [DEBUG] nonebot | Checking for matchers in priority 1...
02-26 20:16:59 [DEBUG] nonebot | Checking for matchers in priority 5...

**Comment by felinae98** [comment]
确定你是群管理或者群主，如果还不行就在.env中指明dev模式看更详细的log

**Comment by Soarniner** [comment]
我是群主，好像机器人这边没有识别@的消息，我看其他正常聊天的消息也是上面那个代码格式
dev模式咋进orz

**Comment by felinae98** [comment]
新建一个.env文件指定ENVIRONMENT https://v2.nonebot.dev/guide/basic-configuration.html

**Comment by Soarniner** [comment]
.env中原来就有ENVIRONMENT=dev
.env.dev中也有DEBUG=true喔

**Comment by felinae98** [comment]
贴下完整日志吧

**Comment by Soarniner** [comment]
PS C:\Users\Administrator\Downloads\PRTS1> nb run
02-26 20:51:36 [INFO] nonebot | NoneBot is initializing...
02-26 20:51:36 [INFO] nonebot | Current Env: dev
02-26 20:51:36 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'),
'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': se
t(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(secon
ds=120), 'environment': 'dev'}
02-26 20:51:36 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
02-26 20:51:36 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
02-26 20:51:36 [INFO] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
02-26 20:51:36 [INFO] nonebot | Succeeded to import "nonebot_hk_reporter"
02-26 20:51:36 [INFO] nonebot | Running NoneBot...
02-26 20:51:36 [DEBUG] nonebot | Loaded adapters: cqhttp
02-26 20:51:36 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
02-26 20:51:36 [INFO] uvicorn | Started reloader process [2840] using statreload
02-26 20:51:37 [INFO] nonebot | NoneBot is initializing...
02-26 20:51:37 [INFO] nonebot | Current Env: dev
02-26 20:51:37 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'),
'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': se
t(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(secon
ds=120), 'environment': 'dev'}
02-26 20:51:37 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
02-26 20:51:37 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
02-26 20:51:37 [INFO] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
02-26 20:51:37 [INFO] nonebot | Succeeded to import "nonebot_hk_reporter"
02-26 20:51:37 [INFO] uvicorn | Started server process [2788]
02-26 20:51:37 [INFO] uvicorn | Waiting for application startup.
02-26 20:51:37 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02-26 20:51:37 [INFO] uvicorn | Application startup complete.
02-26 20:51:56 [INFO] uvicorn | ('127.0.0.1', 49351) - "WebSocket /cqhttp/ws" [accepted]
02-26 20:51:56 [INFO] nonebot | WebSocket Connection from CQHTTP Bot 340*****467 Accepted!
02-26 20:52:06 [INFO] nonebot | CQHTTP 3403*****467 | [message.group.normal]: Message 243350655 from 28*****647@[群:104*******472] "添加订阅"
02-26 20:52:06 [DEBUG] nonebot | Checking for matchers in priority 1...
02-26 20:52:06 [DEBUG] nonebot | Checking for matchers in priority 5...

**Comment by Soarniner** [comment]
另外，prts-forward-bot那边尝试运行也卡住了，我在那边提交了Issues

**Comment by felinae98** [comment]
需要添加一个环境变量`COMMAND_START=[""]`，你是用的插件模式不是直接克隆吧

**Comment by Soarniner** [comment]
感谢，直接克隆运行成功了，只是每给一条消息就会报个错，订阅看起来是正常的。
02-26 21:03:46 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02-26 21:03:46 [INFO] uvicorn | Application startup complete.
02-26 21:03:46 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
02-26 21:04:10 [INFO] uvicorn | ('127.0.0.1', 49334) - "WebSocket /cqhttp/ws" [accepted]
02-26 21:04:10 [INFO] nonebot | WebSocket Connection from CQHTTP Bot 340*****467 Accepted!
02-26 21:04:17 [INFO] nonebot | CQHTTP 3403***467 | [message.group.normal]: Message -1863996964 from 284*****47@[群:104******472] "添加订阅"
02-26 21:04:17 [INFO] nonebot | Event will be handled by <Matcher from hk_reporter, type=message, priority=5, temp=False
>
02-26 21:04:17 [ERROR] nonebot | Failed to handle event. Raw: {'anonymous': None, 'font': 0, 'group_id': 104*******472, 'me
ssage': [{'data': {'text': '请输入想要订阅的平台，目前支持：bilibili, weibo, rss'}, 'type': 'text'}], 'message_id': -404
580022, 'message_seq': 245, 'message_type': 'group', 'post_type': 'message_sent', 'raw_message': '请输入想要订阅的平台，
目前支持：bilibili, weibo, rss', 'self_id': 34********467, 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickn
ame': 'PRTS Message', 'role': 'member', 'sex': 'unknown', 'title': '', 'user_id': 3**********67}, 'sub_type': 'normal', 'ti
me': 1614344657, 'user_id': 340*********7}
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __c
all__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in mai
n
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in in
voke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in in
voke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in inv
oke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nb_cli\__init__.py", line 46, in
 run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers.py", line 52, in
 run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nonebot\__init__.py", line 219,
in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nonebot\drivers\fastapi.py", lin
e 160, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 362, in r
un
    server.run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 390, in r
un
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_unti
l_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_fore
ver
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_on
ce
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nonebot\adapters\cqhttp\bot.py",
 line 318, in handle_message
    event = Event.parse_obj(message)
  File "pydantic\main.py", line 520, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Event
post_type
  unexpected value; permitted: 'message', 'notice', 'request', 'meta_event' (type=value_error.const; given=message_sent;
 permitted=('message', 'notice', 'request', 'meta_event'))
02-26 21:04:17 [INFO] nonebot | Matcher <Matcher from hk_reporter, type=message, priority=5, temp=False> running complet
e

**Comment by felinae98** [comment]
你用的nonebot版本是多少

**Comment by Soarniner** [comment]
v2.0.0a10
我的账号刚刚被封了，是被风控了嘛，我还没开那个文字转图像，在群里就发了一个测试消息
现在在下载Chromium，好慢

**Comment by felinae98** [comment]
最新版优化了chromium下载速度，号建议挂7天不然会被风控

**Comment by Soarniner** [comment]
B站测试发现推送不出来
02-27 01:21:11 [INFO] hk_reporter | fetch new post from bilibili 481562758: 496161760276901052
02-27 01:21:11 [ERROR] apscheduler | Job "bilibili_check (trigger: interval[0:00:10], next run at: 2021-02-27 01:21:21 C
ST)" raised an exception
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __c
all__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in mai
n
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in in
voke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in in
voke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in inv
oke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nb_cli\__init__.py", line 46, in
 run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers.py", line 52, in
 run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nonebot\__init__.py", line 219,
in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nonebot\drivers\fastapi.py", lin
e 160, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 362, in r
un
    server.run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 390, in r
un
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_unti
l_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_fore
ver
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_on
ce
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\apscheduler\executors\base_py3.p
y", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "src/plugins\hk_reporter\scheduler.py", line 14, in bilibili_check
    await fetch_and_send('bilibili')
  File "src/plugins\hk_reporter\platform\utils.py", line 38, in fetch_and_send
    send_msgs(bot, user.user, user.user_type, await send_post.generate_messages())
  File "src/plugins\hk_reporter\post.py", line 77, in generate_messages
    msgs.append(await parse_text(text))
  File "src/plugins\hk_reporter\utils.py", line 67, in parse_text
    return await r.text_to_pic_cqcode(text)
  File "src/plugins\hk_reporter\utils.py", line 58, in text_to_pic_cqcode
    data = await self.text_to_pic(text)
  File "src/plugins\hk_reporter\utils.py", line 51, in text_to_pic
    with open('/tmp/text-{}.html'.format(hash_text), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/text-66e56bdeaf2f922a5058.html'

**Comment by felinae98** [comment]
最新版已修复
