### ISSUE TITLE
rss订阅似乎不支持rsshub生成的订阅源

### ISSUE THREAD

**Issue by yoiyami96** [felinae98/nonebot-hk-reporter#3]
rt，像it之家这种本身有订阅源的就可以，rsshub生成的推特时间线订阅源就不行，未来会有可能支持吗？最后感谢大佬开发出这么好的插件。

**Comment by felinae98** [comment]
给下rss链接

**Comment by felinae98** [comment]
然后看一看日志

**Comment by yoiyami96** [comment]
rss链接  https://rsshub.app/twitter/user/shycocoa

03-01 00:21:28 [INFO] nonebot | CQHTTP 3558036990 | [message.group.normal]: Message -869563537 from 1986612158@[群:722970667] "添加订阅"
03-01 00:21:28 [INFO] nonebot | Event will be handled by <Matcher from nonebot_hk_reporter, type=message, priority=5, temp=False>
03-01 00:21:28 [ERROR] nonebot | Failed to handle event. Raw: {'anonymous': None, 'font': 0, 'group_id': 722970667, 'message': '请输入想要订阅的平台，目前支持：bilibili, weibo, rss, arknights', 'message_id': 1380914892, 'message_seq': 1514, 'message_type': 'group', 'post_type': 'message_sent', 'raw_message': '请输入想要订阅的平台，目前支持：bilibili, weibo, rss, arknights', 'self_id': 3558036990, 'sender': {'age': 0, 'area': '', 'card': 'ATRI', 'level': '', 'nickname': 'ATRI', 'role': 'admin', 'sex': 'unknown', 'title': '', 'user_id': 3558036990}, 'sub_type': 'normal', 'time': 1614529288, 'user_id': 3558036990}
Traceback (most recent call last):
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers.py", line 52, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 362, in run
    server.run()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 318, in handle_message
    event = Event.parse_obj(message)
  File "pydantic\main.py", line 520, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Event
post_type
  unexpected value; permitted: 'message', 'notice', 'request', 'meta_event' (type=value_error.const; given=message_sent; permitted=('message', 'notice', 'request', 'meta_event'))
03-01 00:21:28 [INFO] nonebot | Matcher <Matcher from nonebot_hk_reporter, type=message, priority=5, temp=False> running complete
03-01 00:21:33 [INFO] nonebot | CQHTTP 3558036990 | [message.group.normal]: Message 625485402 from 1986612158@[群:722970667] "rss"
03-01 00:21:33 [INFO] nonebot | Event will be handled by <Matcher from nonebot_hk_reporter, type=message, priority=0, temp=True>
03-01 00:21:34 [ERROR] nonebot | Failed to handle event. Raw: {'anonymous': None, 'font': 0, 'group_id': 722970667, 'message': '请输入订阅用户的id，详情查阅https://github.com/felinae98/nonebot-hk-reporter', 'message_id': -1136560160, 'message_seq': 1516, 'message_type': 'group', 'post_type': 'message_sent', 'raw_message': '请输入订阅用户的id，详情查阅https://github.com/felinae98/nonebot-hk-reporter', 'self_id': 3558036990, 'sender': {'age': 0, 'area': '', 'card': 'ATRI', 'level': '', 'nickname': 'ATRI', 'role': 'admin', 'sex': 'unknown', 'title': '', 'user_id': 3558036990}, 'sub_type': 'normal', 'time': 1614529294, 'user_id': 3558036990}
Traceback (most recent call last):
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers.py", line 52, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 362, in run
    server.run()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 318, in handle_message
    event = Event.parse_obj(message)
  File "pydantic\main.py", line 520, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Event
post_type
  unexpected value; permitted: 'message', 'notice', 'request', 'meta_event' (type=value_error.const; given=message_sent; permitted=('message', 'notice', 'request', 'meta_event'))
03-01 00:21:34 [INFO] nonebot | Matcher <Matcher from nonebot_hk_reporter, type=message, priority=0, temp=True> running complete
03-01 00:21:38 [INFO] nonebot | CQHTTP 3558036990 | [message.group.normal]: Message -884586634 from 1986612158@[群:722970667] "https://rsshub.app/twitter/user/shycocoa"
03-01 00:21:38 [INFO] nonebot | Event will be handled by <Matcher from nonebot_hk_reporter, type=message, priority=0, temp=True>
03-01 00:21:48 [INFO] nonebot | Matcher <Matcher from nonebot_hk_reporter, type=message, priority=0, temp=True> running complete
03-01 00:21:48 [ERROR] nonebot | Running matcher <Matcher from nonebot_hk_reporter, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
    yield
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpcore\_async\connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpcore\_backends\asyncio.py", line 270, in open_tcp_stream
    return SocketStream(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers.py", line 52, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 362, in run
    server.run()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\matcher.py", line 527, in run
    await self.run_handler(handler, bot, event, state_)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\nonebot\matcher.py", line 512, in run_handler
    await handler(
  File "src/plugins\nonebot_hk_reporter\config_manager.py", line 37, in add_sub_parse_id
    name = await check_sub_target(state['platform'], target)
  File "src/plugins\nonebot_hk_reporter\platform\utils.py", line 15, in check_sub_target
    return await platform_manager[target_type].get_account_name(target)
  File "src/plugins\nonebot_hk_reporter\platform\rss.py", line 21, in get_account_name
    res = await client.get(target, timeout=10.0)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1548, in get
    return await self.request(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1371, in request
    response = await self.send(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\cyy19\appdata\local\programs\python\python39\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout

**Comment by felinae98** [comment]
服务器连接rsshub timeout，请自行解决代理问题
